# syntax=docker/dockerfile:1

FROM node:16.14-buster

LABEL maintainer="tech1@sumomedia.co"
LABEL app_environment="production"

WORKDIR /home/node

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 3000

RUN npm run build

CMD [ "npm", "run", "start" ]